from sc4pimx.textutil import (
    decode_sc4_string_prop,
    decode_sc4_text,
    encode_sc4_text,
    parse_sc4_xml,
)


def _plugin_desc(name: bytes) -> bytes:
    return (b'<?xml version="1.0" encoding="UTF-8"?>\n'
            b'<!--Generated by BAT-->\n'
            b'<SC4PLUGINDESC Name="' + name + b'" Author="gerandi">\n'
            b'</SC4PLUGINDESC>\n')


def test_parse_sc4_xml_accepts_cp1252_bytes_declared_as_utf8():
    # BAT writes an UTF-8 declaration but 8-bit bytes, e.g. "Friedrichstrasse"
    # spelled with a sharp s (0xDF in cp1252), which expat rejects outright.
    doc = parse_sc4_xml(_plugin_desc(b"Friedrichstra\xdfe 1"))
    assert doc.documentElement.getAttribute("Name") == "Friedrichstraße 1"


def test_parse_sc4_xml_keeps_utf8_payloads_intact():
    doc = parse_sc4_xml(_plugin_desc("Friedrichstraße 1".encode("utf-8")))
    assert doc.documentElement.getAttribute("Name") == "Friedrichstraße 1"


def test_decode_sc4_string_prop_decodes_bytes_without_repr_wrapper():
    assert decode_sc4_string_prop(b"Some item name") == "Some item name"


def test_decode_sc4_string_prop_preserves_latin1_bytes():
    assert decode_sc4_string_prop(b"Caf\xe9") == "Caf\xe9"


def test_sc4_ltext_round_trip_uses_utf16_le_payload():
    text = "Some item name"
    assert decode_sc4_text(encode_sc4_text(text)) == text
